name: ucare
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  faker: ^2.0.0
  flutter:
    sdk: flutter
  get: 4.6.5
  get_cli: ^1.8.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
    - assets/button/
    - assets/barang/
    - assets/bg.png
  uses-material-design: true
